steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/twitter-be', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/twitter-be']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'twitter-be',
      '--image', 'gcr.io/$PROJECT_ID/twitter-be',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--set-env-vars', 'DB_USER=$(DB_USER),DB_PASSWORD=$(DB_PASSWORD),DB_NAME=$(DB_NAME),DB_HOST=$(DB_HOST),PORT=$(PORT)'
    ]

images:
  - 'gcr.io/$PROJECT_ID/twitter-be'
